"""Create the remaining MVP core data model.

Revision ID: 0002_mvp_core
Revises: 0001_week1
Create Date: 2026-08-30 16:22:44.398721
"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

revision: str = "0002_mvp_core"
down_revision: str | None = "0001_week1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bad_cases",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "MESSAGE",
                "EVAL_RUN",
                "QUIZ_ATTEMPT",
                "RETRIEVAL_TRACE",
                name="bad_case_source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "FIXED",
                "WONT_FIX",
                name="bad_case_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("reported_by", sa.Uuid(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_bad_cases_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reported_by"],
            ["users.id"],
            name=op.f("fk_bad_cases_reported_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bad_cases")),
        sa.UniqueConstraint(
            "course_id",
            "source_type",
            "source_id",
            "category",
            name="uq_bad_cases_course_source_category",
        ),
    )
    with op.batch_alter_table("bad_cases", schema=None) as batch_op:
        batch_op.create_index(
            "ix_bad_cases_course_category", ["course_id", "category"], unique=False
        )
        batch_op.create_index(
            "ix_bad_cases_course_status", ["course_id", "status"], unique=False
        )

    op.create_table(
        "chat_sessions",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("index_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ARCHIVED",
                name="chat_session_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "index_version > 0", name=op.f("ck_chat_sessions_index_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_chat_sessions_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_chat_sessions_student_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_sessions")),
    )
    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chat_sessions_student_course_status",
            ["student_id", "course_id", "status"],
            unique=False,
        )

    op.create_table(
        "course_indexes",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "dense_status",
            sa.Enum(
                "PENDING",
                "BUILDING",
                "READY",
                "FAILED",
                name="index_dense_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "lexical_status",
            sa.Enum(
                "PENDING",
                "BUILDING",
                "READY",
                "FAILED",
                name="index_lexical_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("lexical_path", sa.String(length=1024), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "BUILDING",
                "READY",
                "ACTIVE",
                "FAILED",
                "ARCHIVED",
                name="course_index_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("smoke_test_result", sa.JSON(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_course_indexes_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_indexes_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_indexes")),
        sa.UniqueConstraint(
            "course_id", "version", name="uq_course_indexes_course_version"
        ),
    )
    with op.batch_alter_table("course_indexes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_course_indexes_course_status", ["course_id", "status"], unique=False
        )
        batch_op.create_index(
            "uq_course_indexes_one_active",
            ["course_id"],
            unique=True,
            postgresql_where=sa.text("status = 'ACTIVE'"),
            sqlite_where=sa.text("status = 'ACTIVE'"),
        )

    op.create_table(
        "documents",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("logical_name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ARCHIVED",
                name="document_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_documents_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint(
            "course_id", "logical_name", name="uq_documents_course_logical_name"
        ),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_documents_course_status", ["course_id", "status"], unique=False
        )

    op.create_table(
        "eval_datasets",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "RETRIEVAL",
                "END_TO_END_QA",
                "INTENT_ROUTING",
                "LEARNING_PATH",
                name="eval_dataset_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "FROZEN",
                "ARCHIVED",
                name="eval_dataset_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_eval_datasets_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_eval_datasets_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_eval_datasets_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_datasets")),
        sa.UniqueConstraint(
            "course_id", "type", "version", name="uq_eval_datasets_course_type_version"
        ),
    )
    with op.batch_alter_table("eval_datasets", schema=None) as batch_op:
        batch_op.create_index(
            "ix_eval_datasets_course_status", ["course_id", "status"], unique=False
        )

    op.create_table(
        "graph_outbox",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("deduplication_key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "SUCCEEDED",
                "FAILED",
                "DEAD_LETTER",
                name="graph_outbox_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "retry_count >= 0", name=op.f("ck_graph_outbox_retry_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_graph_outbox_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_outbox")),
        sa.UniqueConstraint(
            "deduplication_key", name="uq_graph_outbox_deduplication_key"
        ),
    )
    with op.batch_alter_table("graph_outbox", schema=None) as batch_op:
        batch_op.create_index("ix_graph_outbox_course_id", ["course_id"], unique=False)
        batch_op.create_index(
            "ix_graph_outbox_status_available", ["status", "available_at"], unique=False
        )

    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=127), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "PROCESSING",
                "READY_FOR_REVIEW",
                "PUBLISHED",
                "FAILED",
                "ARCHIVED",
                name="document_version_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_document_versions_size_bytes_nonnegative")
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_document_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint(
            "document_id", "sha256", name="uq_document_versions_document_sha256"
        ),
        sa.UniqueConstraint(
            "document_id", "version", name="uq_document_versions_document_version"
        ),
    )
    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_document_versions_document_status",
            ["document_id", "status"],
            unique=False,
        )

    op.create_table(
        "eval_cases",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("case_key", sa.String(length=255), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("expected", sa.JSON(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ARCHIVED",
                name="record_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["eval_datasets.id"],
            name=op.f("fk_eval_cases_dataset_id_eval_datasets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_cases")),
        sa.UniqueConstraint(
            "dataset_id", "case_key", name="uq_eval_cases_dataset_case_key"
        ),
    )
    with op.batch_alter_table("eval_cases", schema=None) as batch_op:
        batch_op.create_index(
            "ix_eval_cases_dataset_status", ["dataset_id", "status"], unique=False
        )

    op.create_table(
        "eval_runs",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="eval_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("git_commit", sa.String(length=64), nullable=False),
        sa.Column("index_version", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["eval_datasets.id"],
            name=op.f("fk_eval_runs_dataset_id_eval_datasets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_runs")),
    )
    with op.batch_alter_table("eval_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_eval_runs_dataset_status", ["dataset_id", "status"], unique=False
        )
        batch_op.create_index("ix_eval_runs_trace_id", ["trace_id"], unique=False)

    op.create_table(
        "messages",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "USER",
                "ASSISTANT",
                "SYSTEM",
                name="message_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "intent",
            sa.Enum(
                "TUTOR_QA",
                "CONCEPT_COMPARE",
                "DIAGNOSE",
                "QUIZ",
                "LEARNING_PATH",
                name="agent_intent",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("trace_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "FAILED",
                name="message_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
            name=op.f("fk_messages_session_id_chat_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_session_created", ["session_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_messages_trace_id", ["trace_id"], unique=False)

    op.create_table(
        "chunks",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section_path", sa.JSON(), nullable=False),
        sa.Column("title_level", sa.Integer(), nullable=True),
        sa.Column(
            "chunk_type",
            sa.Enum(
                "TEXT",
                "LIST",
                "TABLE",
                "CODE_BLOCK",
                "FORMULA",
                "EXAMPLE",
                "ANSWER",
                "LAB_STEP",
                name="chunk_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("previous_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("next_chunk_id", sa.Uuid(), nullable=True),
        sa.Column(
            "embedding",
            Vector(1024).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ARCHIVED",
                name="record_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "char_count >= 0", name=op.f("ck_chunks_char_count_nonnegative")
        ),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_chunks_ordinal_nonnegative")),
        sa.CheckConstraint(
            "page IS NULL OR page > 0", name=op.f("ck_chunks_page_positive")
        ),
        sa.ForeignKeyConstraint(
            ["next_chunk_id"],
            ["chunks.id"],
            name=op.f("fk_chunks_next_chunk_id_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["previous_chunk_id"],
            ["chunks.id"],
            name=op.f("fk_chunks_previous_chunk_id_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["document_versions.id"],
            name=op.f("fk_chunks_version_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("version_id", "ordinal", name="uq_chunks_version_ordinal"),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chunks_next_chunk_id", ["next_chunk_id"], unique=False
        )
        batch_op.create_index(
            "ix_chunks_previous_chunk_id", ["previous_chunk_id"], unique=False
        )
        batch_op.create_index(
            "ix_chunks_version_page", ["version_id", "page"], unique=False
        )
        batch_op.create_index(
            "ix_chunks_version_status", ["version_id", "status"], unique=False
        )

    op.create_table(
        "ingestion_jobs",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "QUEUED",
                "PARSING",
                "CHUNKING",
                "EMBEDDING",
                "LEXICAL_INDEXING",
                "GRAPH_EXTRACTING",
                "VALIDATING",
                "READY_FOR_REVIEW",
                "PUBLISHED",
                "FAILED",
                "CANCELLED",
                name="ingestion_stage",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("stage_details", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100",
            name=op.f("ck_ingestion_jobs_progress_percentage"),
        ),
        sa.CheckConstraint(
            "retry_count >= 0", name=op.f("ck_ingestion_jobs_retry_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["document_versions.id"],
            name=op.f("fk_ingestion_jobs_version_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
        sa.UniqueConstraint("version_id", name="uq_ingestion_jobs_version_id"),
    )
    with op.batch_alter_table("ingestion_jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ingestion_jobs_stage_updated", ["stage", "updated_at"], unique=False
        )

    op.create_table(
        "citations",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("claim_index", sa.Integer(), nullable=False),
        sa.Column("label", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ARCHIVED",
                name="record_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "claim_index >= 0", name=op.f("ck_citations_claim_index_nonnegative")
        ),
        sa.CheckConstraint("label > 0", name=op.f("ck_citations_label_positive")),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("fk_citations_chunk_id_chunks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_citations_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_citations")),
        sa.UniqueConstraint(
            "message_id",
            "claim_index",
            "chunk_id",
            name="uq_citations_message_claim_chunk",
        ),
        sa.UniqueConstraint("message_id", "label", name="uq_citations_message_label"),
    )
    with op.batch_alter_table("citations", schema=None) as batch_op:
        batch_op.create_index("ix_citations_chunk_id", ["chunk_id"], unique=False)

    op.create_table(
        "concept_candidates",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("index_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("extraction_model", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "MERGED",
                name="review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("merged_into_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_concept_candidates_confidence_probability"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_concept_candidates_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["index_id"],
            ["course_indexes.id"],
            name=op.f("fk_concept_candidates_index_id_course_indexes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_candidate_id"],
            ["concept_candidates.id"],
            name=op.f(
                "fk_concept_candidates_merged_into_candidate_id_concept_candidates"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_concept_candidates_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["chunks.id"],
            name=op.f("fk_concept_candidates_source_chunk_id_chunks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concept_candidates")),
    )
    with op.batch_alter_table("concept_candidates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_concept_candidates_course_status", ["course_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_concept_candidates_index_id", ["index_id"], unique=False
        )
        batch_op.create_index(
            "ix_concept_candidates_source_chunk_id", ["source_chunk_id"], unique=False
        )

    op.create_table(
        "quiz_items",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "EASY",
                "MEDIUM",
                "HARD",
                name="quiz_difficulty",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "MERGED",
                name="review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("generation_model", sa.String(length=255), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concept_candidates.id"],
            name=op.f("fk_quiz_items_concept_id_concept_candidates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_quiz_items_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_quiz_items_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["chunks.id"],
            name=op.f("fk_quiz_items_source_chunk_id_chunks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_items")),
    )
    with op.batch_alter_table("quiz_items", schema=None) as batch_op:
        batch_op.create_index(
            "ix_quiz_items_concept_status", ["concept_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_quiz_items_course_status", ["course_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_quiz_items_source_chunk_id", ["source_chunk_id"], unique=False
        )

    op.create_table(
        "quiz_attempts",
        sa.Column("quiz_item_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUBMITTED",
                "GRADED",
                "INVALIDATED",
                name="quiz_attempt_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("weight > 0", name=op.f("ck_quiz_attempts_weight_positive")),
        sa.ForeignKeyConstraint(
            ["quiz_item_id"],
            ["quiz_items.id"],
            name=op.f("fk_quiz_attempts_quiz_item_id_quiz_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_quiz_attempts_student_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_attempts")),
        sa.UniqueConstraint(
            "student_id",
            "idempotency_key",
            name="uq_quiz_attempts_student_idempotency_key",
        ),
    )
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_quiz_attempts_quiz_student",
            ["quiz_item_id", "student_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_quiz_attempts_student_created",
            ["student_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "relation_candidates",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("from_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("to_candidate_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "PREREQUISITE_OF",
                "RELATED_TO",
                "PART_OF",
                "CONTRASTS_WITH",
                name="relation_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("extraction_model", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "MERGED",
                name="review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_relation_candidates_confidence_probability"),
        ),
        sa.CheckConstraint(
            "from_candidate_id <> to_candidate_id",
            name=op.f("ck_relation_candidates_no_candidate_self_loop"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_relation_candidates_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["from_candidate_id"],
            ["concept_candidates.id"],
            name=op.f("fk_relation_candidates_from_candidate_id_concept_candidates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_relation_candidates_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["chunks.id"],
            name=op.f("fk_relation_candidates_source_chunk_id_chunks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_candidate_id"],
            ["concept_candidates.id"],
            name=op.f("fk_relation_candidates_to_candidate_id_concept_candidates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relation_candidates")),
        sa.UniqueConstraint(
            "from_candidate_id",
            "to_candidate_id",
            "type",
            "source_chunk_id",
            name="uq_relation_candidates_edge_source",
        ),
    )
    with op.batch_alter_table("relation_candidates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_relation_candidates_course_status",
            ["course_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            "ix_relation_candidates_source_chunk_id", ["source_chunk_id"], unique=False
        )

    op.create_table(
        "mastery_states",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.Column("alpha", sa.Float(), nullable=False),
        sa.Column("beta", sa.Float(), nullable=False),
        sa.Column(
            "mastery",
            sa.Float(),
            sa.Computed("alpha / (alpha + beta)", persisted=True),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_assessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ARCHIVED",
                name="record_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("alpha > 0", name=op.f("ck_mastery_states_alpha_positive")),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name=op.f("ck_mastery_states_attempt_count_nonnegative"),
        ),
        sa.CheckConstraint("beta > 0", name=op.f("ck_mastery_states_beta_positive")),
        sa.CheckConstraint(
            "mastery >= 0 AND mastery <= 1",
            name=op.f("ck_mastery_states_mastery_probability"),
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concept_candidates.id"],
            name=op.f("fk_mastery_states_concept_id_concept_candidates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_mastery_states_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["last_attempt_id"],
            ["quiz_attempts.id"],
            name=op.f("fk_mastery_states_last_attempt_id_quiz_attempts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_mastery_states_student_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mastery_states")),
        sa.UniqueConstraint(
            "course_id",
            "student_id",
            "concept_id",
            name="uq_mastery_states_course_student_concept",
        ),
    )
    with op.batch_alter_table("mastery_states", schema=None) as batch_op:
        batch_op.create_index(
            "ix_mastery_states_course_concept",
            ["course_id", "concept_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_mastery_states_student_course",
            ["student_id", "course_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mastery_states", schema=None) as batch_op:
        batch_op.drop_index("ix_mastery_states_student_course")
        batch_op.drop_index("ix_mastery_states_course_concept")

    op.drop_table("mastery_states")
    with op.batch_alter_table("relation_candidates", schema=None) as batch_op:
        batch_op.drop_index("ix_relation_candidates_source_chunk_id")
        batch_op.drop_index("ix_relation_candidates_course_status")

    op.drop_table("relation_candidates")
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_quiz_attempts_student_created")
        batch_op.drop_index("ix_quiz_attempts_quiz_student")

    op.drop_table("quiz_attempts")
    with op.batch_alter_table("quiz_items", schema=None) as batch_op:
        batch_op.drop_index("ix_quiz_items_source_chunk_id")
        batch_op.drop_index("ix_quiz_items_course_status")
        batch_op.drop_index("ix_quiz_items_concept_status")

    op.drop_table("quiz_items")
    with op.batch_alter_table("concept_candidates", schema=None) as batch_op:
        batch_op.drop_index("ix_concept_candidates_source_chunk_id")
        batch_op.drop_index("ix_concept_candidates_index_id")
        batch_op.drop_index("ix_concept_candidates_course_status")

    op.drop_table("concept_candidates")
    with op.batch_alter_table("citations", schema=None) as batch_op:
        batch_op.drop_index("ix_citations_chunk_id")

    op.drop_table("citations")
    with op.batch_alter_table("ingestion_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_ingestion_jobs_stage_updated")

    op.drop_table("ingestion_jobs")
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_chunks_version_status")
        batch_op.drop_index("ix_chunks_version_page")
        batch_op.drop_index("ix_chunks_previous_chunk_id")
        batch_op.drop_index("ix_chunks_next_chunk_id")

    op.drop_table("chunks")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_trace_id")
        batch_op.drop_index("ix_messages_session_created")

    op.drop_table("messages")
    with op.batch_alter_table("eval_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_eval_runs_trace_id")
        batch_op.drop_index("ix_eval_runs_dataset_status")

    op.drop_table("eval_runs")
    with op.batch_alter_table("eval_cases", schema=None) as batch_op:
        batch_op.drop_index("ix_eval_cases_dataset_status")

    op.drop_table("eval_cases")
    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.drop_index("ix_document_versions_document_status")

    op.drop_table("document_versions")
    with op.batch_alter_table("graph_outbox", schema=None) as batch_op:
        batch_op.drop_index("ix_graph_outbox_status_available")
        batch_op.drop_index("ix_graph_outbox_course_id")

    op.drop_table("graph_outbox")
    with op.batch_alter_table("eval_datasets", schema=None) as batch_op:
        batch_op.drop_index("ix_eval_datasets_course_status")

    op.drop_table("eval_datasets")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index("ix_documents_course_status")

    op.drop_table("documents")
    with op.batch_alter_table("course_indexes", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_course_indexes_one_active",
            postgresql_where=sa.text("status = 'ACTIVE'"),
            sqlite_where=sa.text("status = 'ACTIVE'"),
        )
        batch_op.drop_index("ix_course_indexes_course_status")

    op.drop_table("course_indexes")
    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_sessions_student_course_status")

    op.drop_table("chat_sessions")
    with op.batch_alter_table("bad_cases", schema=None) as batch_op:
        batch_op.drop_index("ix_bad_cases_course_status")
        batch_op.drop_index("ix_bad_cases_course_category")

    op.drop_table("bad_cases")
    # ### end Alembic commands ###
